### ISSUE TITLE
Dynamic Host 

### ISSUE THREAD

**Issue by mdy007** [iamvishnuks/xmigrate#46]
Hi Vishnu and Team,

The project is awesome and the layout of the project designed in the world-class.
myself a DevOps/Cloudops engineer and much interested to contribute on Devops/Ansible,

* I believe dynamic hosting is not enabled, giving the hostname and password (mandatory) is not advanced one

![image](https://user-images.githubusercontent.com/34213219/103738338-de5d6800-5019-11eb-8192-408139597f49.png)
*So, we can take users input as dynamic one (as above) or we can go for dynamic hosting.

Thanks,
S.Mohamed,
CloudOps Engineer.

**Comment by iamvishnuks** [comment]
Hi @mdy007,

Inventory file for ansible will be created only after the user inputs the server ip's, username and password. Hence by design, it's dynamic. The host file which is present in `ansible/hosts` is a dummy file. Hope you understood. And thanks for stopping by 🙏.

**Comment by mdy007** [comment]
Hi Vishnu,

Thank u for the clarity.

And always most welcome
